version: '3.8'

services:
  app:
    container_name: node_container
    env_file:
      - .env
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    container_name: db_container
    image: arm64v8/mongo:4.0
    platform: linux/arm64/v8
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
