scalar Upload

type Product {
  _id: ID!
  vintage: String!
  name: String!
  producerId: ID!
  producer: Producer!
}

type Producer {
  _id: ID!
  name: String!
  country: String
  region: String
}

type Query {
  getProductById(id: ID!): Product
  getProductsByProducerId(producerId: ID!): [Product]
}

input UpdateProductInput {
  id: ID!
  vintage: String
  name: String
  producerId: ID
}

type Mutation {
  importProductsFromCSV(file: Upload!): Boolean!
  updateProductById(input: UpdateProductInput!): Product
  deleteProductsByIds(ids: [ID]!): Boolean
}
